Repository PetDoctor/PetDoctor, pull requests merged in 2022-09, with the labels that each got.

#24 Feature/#23 type to interface 변경
  client/src/apis/hospital/Hospital.ts
  client/src/apis/hospital/HospitalTypes.ts
  client/src/apis/reservation/Reservation.ts
  client/src/apis/reservation/ReserveTypes.ts
  client/src/apis/user/User.ts
  client/src/apis/user/UserTypes.ts
  client/src/components/book/ResModal.tsx
  client/src/components/book/ReservationContent.tsx
  client/src/components/detail/TimeButton.tsx
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/detail/HospitalService.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/pet-information/AddPet.tsx
  client/src/pages/pet-information/PetCard.tsx
  client/src/pages/pet-information/PetInformation.tsx
  client/src/pages/user-info/UserInfo.tsx
  client/src/pages/user-reserv/ReserveCard.tsx
  client/src/pages/user-reserv/UserReserve.tsx
  client/src/state/HospitalState.tsx
  client/src/state/UserState.tsx
  client/src/utils/PrivateRouter.tsx
  package-lock.json
  package.json
  server/src/db/models/UserModel.ts
  server/src/types/UserTypes.ts
  yarn.lock
Labels: 🖥 Frontend, 🛠 Refactor

#26 Feat/#25 화살표 함수로 통일 & React.FC 제거
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/Layout.tsx
  client/src/components/LayoutSearch.tsx
  client/src/components/Search.tsx
  client/src/components/SearchBar.tsx
  client/src/components/main/MainCard.tsx
  client/src/components/main/MainKeyWord.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/Pagenation.tsx
  client/src/pages/home/TagList.tsx
  client/src/pages/home/Tags.tsx
  client/src/pages/hospital-reserve/HospitalReserve.tsx
  client/src/pages/hospital-reserve/ReserveCard.tsx
  client/src/pages/register/Postcode.tsx
  client/src/pages/register/Register.tsx
  client/src/pages/register/RegisterForm.tsx
  client/src/pages/register/Title.tsx
  client/src/styles/style.d.ts
Labels: 🖥 Frontend, 🛠 Refactor

#34 Feature/#31: 로그인 회원가입 반응형 추가
  client/src/pages/login/LoginStyle.tsx
  client/src/pages/register/Register.tsx
  client/src/styles/Colors.tsx
  client/src/styles/style.d.ts
Labels: 🖥 Frontend, 🛠 Refactor

#33 feature/#32: 상세페이지 반응형 추가
  client/src/components/Header.tsx
  client/src/components/Layout.tsx
  client/src/components/Modal.tsx
  client/src/pages/detail/CalendarStyle.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/detail/DetailStyle.tsx
  client/src/pages/detail/Reservation.tsx
  client/src/styles/style.d.ts
Labels: 🖥 Frontend

#30 [#28]refactor: 화살표함수 rules 적용 및 변경
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/components/buttons/CheckBox.tsx
  client/src/components/buttons/RadioBtn.tsx
  client/src/pages/admin-hplist/AdminHospitalList.tsx
  client/src/pages/admin-hplist/HpCard.tsx
  client/src/pages/admin-mypage/AdminMypage.tsx
  client/src/pages/admin-reserv/AdminPagination.tsx
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/hospital-mypage/HospitalMypage.tsx
  client/src/pages/login/Login.tsx
  client/src/pages/pet-information/AddPet.tsx
  client/src/pages/pet-information/PetCard.tsx
  client/src/pages/pet-information/PetInformation.tsx
  client/src/pages/user-info/UserInfo.tsx
  client/src/pages/user-mypage/UserMypage.tsx
  client/src/pages/user-reserv/ReserveCard.tsx
  client/src/pages/user-reserv/UserReserve.tsx
Labels: 🔧 enhancement, 🖥 Frontend
