Repository PetDoctor/PetDoctor, pull requests merged in 2022-08, with the labels that each got.

#8 feature/#6 : 병원 정보 수정 페이지 기초 디자인
  client/src/pages/hospital-info/Constants.tsx
  client/src/pages/hospital-info/HospitalInfo.tsx
  client/src/pages/hospital-info/InfoContent.tsx
  client/src/pages/hospital-info/Interface.tsx
  client/src/pages/hospital-info/Style.tsx
Labels: 🔨 Feature, 🖥 Frontend, ❗️high-priority

#16 Feature/#5 병원 예약 조회 완성 & 타입 재지정 필요
  client/src/pages/hospital-reserve/HospitalReserve.tsx
  client/src/pages/hospital-reserve/ReserveCard.tsx
  client/src/pages/pet-information/AddPet.tsx
Labels: 🔨 Feature, 🖥 Frontend

#14 Feature/#7 관심사 분리
  client/src/apis/Axios.ts
  client/src/apis/hospital/Hospital.ts
  client/src/apis/hospital/HospitalTypes.ts
  client/src/apis/reservation/Reservation.ts
  client/src/apis/reservation/ReserveTypes.ts
  client/src/apis/user/User.ts
  client/src/apis/user/UserTypes.ts
  client/src/components/book/ResModal.tsx
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/pet-information/AddPet.tsx
  client/src/pages/pet-information/PetCard.tsx
  client/src/pages/pet-information/PetInfoInterface.tsx
  client/src/pages/pet-information/PetInformation.tsx
  client/src/pages/user-info/Interface.tsx
  client/src/pages/user-info/UserInfo.tsx
  client/src/pages/user-reserv/UserReserve.tsx
Labels: 🔧 enhancement, 🖥 Frontend

#21 Feat/#19 버셀 오류 타입 제거
  client/src/components/SearchBar.tsx
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/hospital-reserve/HospitalReserve.tsx
  client/src/pages/hospital-reserve/ReserveCard.tsx
Labels: 🐛 Bug, 🖥 Frontend

#22 Fix/#19: components/buttons 소문자 변경
  client/src/pages/admin-userlist/AdminUserList.tsx
Labels: 🐛 Bug, 🖥 Frontend
